/**
 * SATENGKA PASUNG EWS — Netlify Build Pre-Process Script
 * Memastikan firebase-config.js siap digunakan sebelum deploy Netlify selesai.
 */

const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, '..', 'firebase-config.js');
const examplePath = path.join(__dirname, '..', 'firebase-config.example.js');

console.log('[NETLIFY BUILD] Memulai build pre-process SATENGKA PASUNG EWS...');

if (fs.existsSync(configPath)) {
  console.log('[NETLIFY BUILD] \u2705 firebase-config.js sudah ada.');
} else if (process.env.FIREBASE_API_KEY && process.env.FIREBASE_PROJECT_ID) {
  console.log('[NETLIFY BUILD] \u2699\ufe0f Membangun firebase-config.js dari Netlify Environment Variables...');
  const configContent = `/**
 * Generated by Netlify Build Script
 */
export const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || 'satengkapasung.firebaseapp.com'}",
  projectId: "${process.env.FIREBASE_PROJECT_ID || 'satengkapasung'}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || '701459980489'}",
  appId: "${process.env.FIREBASE_APP_ID || '1:701459980489:web:c8921023f3b39ca5e12d18'}"
};

export const APP_MODE = 'FIREBASE';
`;
  fs.writeFileSync(configPath, configContent, 'utf-8');
  console.log('[NETLIFY BUILD] \u2705 firebase-config.js berhasil dibuat dari Environment Variables.');
} else if (fs.existsSync(examplePath)) {
  console.log('[NETLIFY BUILD] \u26a0\ufe0f Menyalin konfigurasi standar dari firebase-config.example.js...');
  fs.copyFileSync(examplePath, configPath);
  console.log('[NETLIFY BUILD] \u2705 firebase-config.js berhasil disalin dari template.');
} else {
  console.error('[NETLIFY BUILD] \u274c Gagal menemukan konfigurasi Firebase!');
  process.exit(1);
}

// Verifikasi sintaks adapter
console.log('[NETLIFY BUILD] \u2705 Menjalankan verifikasi sintaks adapter...');
try {
  require('child_process').execSync('node --check js/firebase-adapter.js', { stdio: 'inherit' });
  console.log('[NETLIFY BUILD] \u2705 Sintaks adapter valid.');
} catch (err) {
  console.error('[NETLIFY BUILD] \u274c Gagal memvalidasi sintaks adapter:', err.message);
  process.exit(1);
}

console.log('[NETLIFY BUILD] \u2705 Build Netlify siap dipublikasikan!');
